parameters:
    tests_dir: "../../TESTS/MAIN"
    scratch: "./scratch"
    yambo_dir: ""
    yambo_file: "yambo"
    ypp_file: "ypp"
    nprocs: 2
    mpi_launcher: "mpirun"
    tollerance: 0.1
tests:
    Al_bulk: ["GW-OPTICS"]
    Si_bulk: ["GW-OPTICS"]
    hBN: ["GW-OPTICS"]
    LiF: ["GW-OPTICS"]
